# Copyright 2022 Wayback Archiver. All rights reserved.
# Use of this source code is governed by the GNU GPL v3
# license that can be found in the LICENSE file.
#
# More details see https://render.com/docs/blueprint-spec

services:
 - type: web
   name: wayback-starter
   plan: free
   env: docker
   autoDeploy: false
   healthCheckPath: /healthcheck
   dockerfilePath: ./build/docker/Dockerfile.render
   envVars:
     - key: PORT
       value: 80
     - key: WAYBACK_IPFS_APIKEY
       sync: false
