# Copyright 2020 Wayback Archiver. All rights reserved.
# Use of this source code is governed by the GNU GPL v3
# license that can be found in the LICENSE file.
#
name: wayback

version: 'git'

summary: A toolkit to upload files to IPFS pinning services.

description: |
  A toolkit for snapshot webpage to the Wayback Machine.
  Website https://github.com/wabarc/wayback

base: core20
grade: stable
confinement: strict
compression: lzo

architectures:
  - amd64
  - arm64
  - armhf
  - i386

parts:
  wayback:
    plugin: go
    source: https://github.com/wabarc/wayback.git
    override-build: |
      make build
      install $SNAPCRAFT_PART_BUILD/build/binary/wayback -D $SNAPCRAFT_PART_INSTALL/bin/wayback
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      if [ ! -e $SNAPCRAFT_PART_INSTALL/bin/wayback ]; then
        ln -s $SNAPCRAFT_PART_INSTALL/bin/wayback $SNAPCRAFT_PART_INSTALL/bin/wayback
      fi
    build-packages:
      - build-essential

apps:
  wayback:
    command: bin/wayback
    plugs:
      - home
      - network
      - network-bind
