.\" Manpage for wayback.
.TH "WAYBACK" "5" "April, 2022" "\ \&" "\ \&"

.SH NAME
wayback \- easy and fast to wayback webpage.

.SH SYNOPSIS
\fBwayback\fR [--chatid] [-d|--daemon] [--debug] [-h|--help] [--ia] [--ip] [--is]
        [--ipfs-host] [-m|--ipfs-mode] [-p|--ipfs-port]
        [-t|--token] [--tor] [--tor-key]
        [-c|--config] [--info] [--print]
        [-v|--version]

.SH EXAMPLES
\fBwayback\fR https://www.eff.org https://www.fsf.org
.br
\fBwayback\fR --ia --is -d telegram -t your-telegram-bot-token

.SH DESCRIPTION
\fBwayback\fR is a toolkit for snapshot webpage to Internet Archive, archive.today, IPFS and beyond.

.SH OPTIONS
.PP
.B \-\-chatid
.RS 4
The Telegram public/private channel id to publish archive result\&.
.RE
.PP
.B \-d, \-\-daemon
.RS 4
Run as daemon service, e.g. telegram, web\&.
.RE
.PP
.B \-c, \-\-config
.RS 4
Configuration file path, defaults: ./wayback.conf, ~/wayback.conf, /etc/wayback.conf\&.
.RE
.PP
.B \-\-debug
.RS 4
Enable debug mode. default: false\&.
.RE
.PP
.B \-\-print
.RS 4
Show application configurations. default: false\&.
.RE
.PP
.B \-\-info
.RS 4
Show application information. default: false\&.
.RE
.PP
.B \-h, \-\-help
.RS 4
help for wayback\&.
.RE
.PP
.B \-\-ia
.RS 4
Wayback webpages to Internet Archive\&.
.RE
.PP
.B \-\-ip
.RS 4
Wayback webpages to IPFS. default: false\&.
.RE
.PP
.B \-\-ipfs\-host
.RS 4
IPFS daemon service's host, do not require, unless enable ipfs. default "127.0.0.1"\&.
.RE
.PP
.B \-m, \-\-ipfs\-mode
.RS 4
IPFS mode for preserve webpage, currently supports are daemon and pinner, for the daemon mode which
.br
required run an IPFS service daemon process extra, for the pinner mode which does not require any
.br
third-party program. Uses pinner mode, also can take infura or pinata as pinner service,
.br
more detail on
.UR
https://github.com/wabarc/ipfs-pinner\&.
.RE
.PP
.B \-p, \-\-ipfs\-port
.RS 4
IPFS daemon port. default 5001\&.
.RE
.PP
.B \-t, \-\-token
.RS 4
Telegram Bot API Token\&.
.RE
.PP
.B \-\-tor
.RS 4
Snapshot webpage via Tor proxy\&.
.RE
.PP
.B \-\-tor-key
.RS 4
The private key for Tor hidden service\&.
.RE
.PP
.B \-v, \-\-version
.RS 4
 version for wayback\&.
.RE

.SH ENVIRONMENT
.TP
.B DEBUG
Set the value to 1 to enable debug logs, override "LOG_LEVEL"\&.
.TP
.B LOG_TIME
Display the date and time in log messages\&.
.TP
.B LOG_LEVEL
Log level, supported level are "debug", "info", "warn", "error", "fatal", defaults to "info"\&.
.TP
.B ENABLE_METRICS
Enable metrics collector\&.
.TP
.B WAYBACK_PROXY
Proxy address.\&.
.TP
.B WAYBACK_LISTEN_ADDR
The listen address for the HTTP server. default "0.0.0.0:8964"\&.
.TP
.B CHROME_BIN
Preferred to sets the path to the Chrome executable\&.
.TP
.B CHROME_REMOTE_ADDR
Chrome/Chromium remote debugging address, for screenshot\&.
.TP
.B WAYBACK_IPFS_HOST
IPFS daemon service's host, do not require, unless enable ipfs. default "127.0.0.1". (same as flag --ipfs-host)\&.
.TP
.B WAYBACK_IPFS_PORT
IPFS daemon port. default 5001. (same as flag --ipfs-port)\&.
.TP
.B WAYBACK_IPFS_MODE
IPFS mode for preserve webpage. default: "pinner". (same as flag --ipfs-mode)\&.
.TP
.B WAYBACK_IPFS_TARGET
The IPFS pinning service is used to store files\&.
.TP
.B WAYBACK_IPFS_APIKEY
Apikey of the IPFS pinning service\&.
.TP
.B WAYBACK_IPFS_SECRET
Secret of the IPFS pinning service\&.
.TP
.B WAYBACK_USE_TOR
Snapshot webpage via Tor proxy. (same as flag --tor)\&.
.TP
.B WAYBACK_ENABLE_IA
Enable Internet Archive\&.
.TP
.B WAYBACK_ENABLE_IS
Enable Archive Today (archive.is)\&.
.TP
.B WAYBACK_ENABLE_IP
Enable IPFS\&.
.TP
.B WAYBACK_POOLING_SIZE
Number of worker pool for wayback at once. default 3\&.
.TP
.B WAYBACK_TIMEOUT
Timeout for single wayback request, default 300\&.
.TP
.B WAYBACK_MAX_RETRIES
Max retries for single wayback request, default 2\&.
.TP
.B WAYBACK_USERAGENT
User-Agent for a wayback request, default WaybackArchiver/1.0\&.
.TP
.B WAYBACK_FALLBACK
Use Google cache as a fallback if the original webpage is unavailable, default "off"\&.
.TP
.B WAYBACK_MEILI_ENDPOINT
Meilisearch API endpoint.\&.
.TP
.B WAYBACK_MEILI_INDEXING
Meilisearch indexing name.\&.
.TP
.B WAYBACK_MEILI_APIKEY
Meilisearch admin API key.\&.
.TP
.B WAYBACK_OMNIVORE_APIKEY
Omnivore API key.\&.
.TP
.B WAYBACK_BOLT_PATH
File path of bolt database. default ./wayback.db\&.
.TP
.B WAYBACK_STORAGE_DIR
Directory to store binary file, e.g. PDF, html file\&.
.TP
.B WAYBACK_MAX_MEDIA_SIZE
Max size to limit download stream media. default 512MB\&.
.TP
.B WAYBACK_MEDIA_SITES
Extra media websites wish to be supported, separate with comma\&.
.TP
.B WAYBACK_TELEGRAM_TOKEN
Telegram Bot API Token. (same as flag --token)\&.
.TP
.B WAYBACK_TELEGRAM_CHANNEL
The chatid which publish message. (same as flag --chatid)\&.
.TP
.B WAYBACK_TELEGRAM_HELPTEXT
The help text for Telegram bot command\&.
.TP
.B WAYBACK_ONION_PRIVKEY
The private key for Tor service. (same as flag --tor-key)\&.
.TP
.B WAYBACK_MASTODON_SERVER
Domain of Mastodon instance\&.
.TP
.B WAYBACK_MASTODON_KEY
The client key of your Mastodon application\&.
.TP
.B WAYBACK_MASTODON_SECRET
The client secret of your Mastodon application\&.
.TP
.B WAYBACK_MASTODON_TOKEN
The access token of your Mastodon application\&.
.TP
.B WAYBACK_MASTODON_CW
Whether specified content warning\&.
.TP
.B WAYBACK_MASTODON_CWTEXT
The text of content warning\&.
.TP
.B WAYBACK_TWITTER_CONSUMER_KEY
The customer key of your Twitter application\&.
.TP
.B WAYBACK_TWITTER_CONSUMER_SECRET
The customer secret of your Twitter application\&.
.TP
.B WAYBACK_TWITTER_ACCESS_TOKEN
The access token of your Twitter application\&.
.TP
.B WAYBACK_TWITTER_ACCESS_SECRET
The access secret of your Twitter application\&.
.TP
.B WAYBACK_DISCORD_BOT_TOKEN
Discord bot authorization token\&.
.TP
.B WAYBACK_DISCORD_CHANNEL
Discord channel ID\&.
.TP
.B WAYBACK_SLACK_APP_TOKEN
App-Level Token of Slack app\&.
.TP
.B WAYBACK_SLACK_BOT_TOKEN
`Bot User OAuth Token` for Slack workspace, use `User OAuth Token` if requires create external link\&.
.TP
.B WAYBACK_SLACK_CHANNEL
Channel ID of Slack channel\&.
.TP
.B WAYBACK_SLACK_HELPTEXT
The help text for Slack slash command\&.
.TP
.B WAYBACK_XMPP_JID
The JID of a XMPP account\&.
.TP
.B WAYBACK_XMPP_PASSWORD
The password of a XMPP account\&.
.TP
.B WAYBACK_XMPP_NOTLS
Connect to XMPP server without TLS\&.
.TP
.B WAYBACK_XMPP_HELPTEXT
The help text for XMPP command\&.
.TP
.B WAYBACK_IRC_NICK
IRC nick\&.
.TP
.B WAYBACK_IRC_NAME
IRC name\&.
.TP
.B WAYBACK_IRC_PASSWORD
IRC password\&.
.TP
.B WAYBACK_IRC_CHANNEL
IRC channel\&.
.TP
.B WAYBACK_IRC_SERVER
IRC server, defaults to `irc.libera.chat:6697`\&.
.TP
.B WAYBACK_GITHUB_TOKEN
GitHub Personal Access Token, required the `repo` scope\&.
.TP
.B WAYBACK_GITHUB_OWNER
GitHub account name\&.
.TP
.B WAYBACK_GITHUB_REPO
GitHub repository to publish results\&.
.TP
.B WAYBACK_NOTION_TOKEN
Notion integration token\&.
.TP
.B WAYBACK_NOTION_DATABASE_ID
Notion database ID for archiving results\&.
.TP
.B WAYBACK_NOSTR_RELAY_URL
Nostr relay server url, multiple separated by comma\&.
.TP
.B WAYBACK_NOSTR_PRIVATE_KEY
The private key of a Nostr account\&.
.TP
.B WAYBACK_ONION_LOCAL_PORT
Local port of Tor service. This is ignored if `WAYBACK_LISTEN_ADDR` is set.\&.
.TP
.B WAYBACK_ONION_REMOTE_PORTS
Remote ports of Tor hidden service, e.g. WAYBACK_ONION_REMOTE_PORTS=80,81\&.
.TP
.B WAYBACK_ONION_DISABLED
Disable onion service. default: false\&.
.TP
.B WAYBACK_SLOT
Pinning service for IPFS mode of pinner, see
.UR
https://github.com/wabarc/ipfs-pinner#supported-pinning-services\&.
.TP
.B WAYBACK_APIKEY
API key for pinning service\&.
.TP
.B WAYBACK_SECRET
API secret for pinning service\&.
.TP
.B WAYBACK_PRIVACY_URL
Privacy policy URL. default: https://wabarc.eu.org/privacy\&.

.SH BUGS
.P
To view a list of known bugs, or to enter a bug report, please use
Wayback's issue tracker: <https://github.com/wabarc/wayback/issues>

.SH AUTHORS
.P
Wayback is written and maintained by Wayback Archiver\&.

.SH "COPYRIGHT"
.P
Wayback is released under the terms of the GNU General Public License v3.0\&.
